### ISSUE TITLE
Invalid syntax error

### ISSUE THREAD

**Issue by Slad3G** [TheSecEng/NessusParser-Excel#1]
Hi,

Thanks for taking the time to port this into Python. I'm looking forward to using it. I did receive the following error:

File "nessusparser.py", line 1000
    REPORT_NAME = "{0}_{1}".format(ARGS.output_file, f"{datetime.now():%Y-%m-%d-%S-%s}")
                                                                                                                                                      ^
SyntaxError: invalid syntax

I am attempting to fix the syntax to see what will work but so far nothing is helping.

Thanks again,

SG

**Comment by Slad3G** [comment]
As an FYI I was running this in Kali Linux in Python 2.7.15 which is the current native version. Changing the line to:

REPORT_NAME = "{0}_{1}".format(ARGS.output_file, f("{datetime.now():%Y-%m-%d-%S-%s}"))

Makes it work flawlessly.

Thanks again,

S

**Comment by TerminalFi** [comment]
Thanks for submitting this, I'll look into making this support both python 3 and 2 fully.

**Comment by TerminalFi** [comment]
Working to fix all issues of Python2 and 3 support.

**Comment by TerminalFi** [comment]
Thanks @Slad3G Fixed in master branch
