### ISSUE TITLE
Ask for improvement

### ISSUE THREAD

**Issue by nimda2k** [TheSecEng/NessusParser-Excel#2]
Hi,

Thanks for your work and taking the time to port this into Python.
I want to ask for improvement. 
Can you add an option for creating separated xlsx'es for each .nessus file in worked directory?

Thank you in  advance.

**Comment by TerminalFi** [comment]
nimda2k, thanks for the request. I will get this done shortly

**Comment by TerminalFi** [comment]
@nimda2k I am rewriting this tool in Go and it will be platform independent. This version will contain the feature you are asking for.
